import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import RouteLayoutShell from "@/components/route-layout-shell";
import { Toaster } from "@/components/ui/sonner";
import SmoothScrollProvider from "@/components/animations/smooth-scroll-provider";

import QueryProvider from "@/context/queryProvider";
import { AuthProvider } from "@/context/authcontext";
import ChatWidget from "@/components/chatbot/ChatWidget";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body suppressHydrationWarning className="min-h-full flex flex-col">
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <SmoothScrollProvider />
          <QueryProvider>
            <AuthProvider>
              <RouteLayoutShell>{children}
                <ChatWidget />
              </RouteLayoutShell>
              <Toaster />
            </AuthProvider>
          </QueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
